### ISSUE TITLE
通过API更改PodGroup运行时的具体Spec配置信息

### ISSUE THREAD

**Issue by rmrf** [laincloud/deployd#4]
我们在更新webrouter (deploy一个自己的version) 的时候出了问题：
deploy 命令触发之后，webrouter down，console也无法访问了，因此新version的webrouter无法从registery下载回来：进入依赖循环。

因此我尝试通过API更改PodGroup运行时的具体Spec配置信息
先通过api获取到webrouter的podgroups信息

```
  curl "http://deployd.lain:9003/api/podgroups?name=webrouter.worker.worker"
```

然后提取出其中的Specs (等效于下面的命令)

```
  curl "http://deployd.lain:9003/api/podgroups?name=webrouter.worker.worker" | jq '.Spec' > new.json
```

接下来修改new.json，将其中的image 信息，release信息都修改为原来的版本。
通过PATCH来尝试让deployd重新部署老的版本的webrouter。

```
curl -XPATCH "http://deployd.lain:9003/api/podgroups?name=webrouter.worker.worker&cmd=spec" -d @new.json
{
"message": "Bad parameter format for PodSpec, EOF",
"data": "Bad parameter format for PodSpec, EOF"
}
```

报错如上。

请问如何构造合法的PodSpec ,可以用于修改PodGroup运行时的具体Spec配置信息。

**Comment by rmrf** [comment]
btw，webrouter的问题已经通过修改image name 的方式绕过去恢复了。但如何通过deployd API来修改 podGroup 日后也许会很有用。

**Comment by rmrf** [comment]
@panli889

**Comment by panli889** [comment]
@rmrf webrouter 做了 HA 的话，升级的时候应该可以自举；没有做 HA 的话，升级前得在 webrouter 所在节点先将所需版本的 release image 拉取下来（webrouter 有 volume，所以升级的时候不会飘走）；

另外，可以这样直接调用 deployd api：

```
1. curl "http://deployd.lain:9003/api/podgroups?name=webrouter.worker.worker" | jq '.Spec.Pod' > new.json
2. curl -XPATCH "http://deployd.lain:9003/api/podgroups?name=webrouter.worker.worker&cmd=spec" -H "Content-Type: application/json" -d @new.json
```

**Comment by rmrf** [comment]
好的，多谢！顺便问一下关于扩内存的问题。
 lain.yml中对于proc内存的修改，似乎并不会生效，即便undeploy并重新deploy也不行，线上生效的依旧是此前在lain.yml 中记录的内存数值。只有通过lain scale来修改，请问是这样的么？

**Comment by panli889** [comment]
@rmrf 是的，集群会记录 proc 当前使用的 内存 和 cpu，如果只是升级的话都会沿用线上的设置，并不会使用 lain.yaml 中的设置，需要更改的话需要通过 lain scale 进行处理

**Comment by rmrf** [comment]
收到，谢谢！
