### ISSUE TITLE
webrouter和新部署的容器不通

### ISSUE THREAD

**Issue by yuyang0** [laincloud/deployd#41]
deployd报：

> podgroup_ops.go:56: Some pods lost IP, will not save pod group /lain/deployd/pod_groups/books/books.web.web

这是什么原因，iptables中好像也没有对应ip的规则，这是什么原因？

**Comment by supermeng** [comment]
这个是因为你容器没有分配到ip，所以不会刷新/lain/deployd/pod_groups/books/books.web.web的数据，以免webrouter刷错配置。具体网络不通需要通过calicoctl get profile $NETWORK --output=yaml查看calico规则是否有问题。
