### ISSUE TITLE
Refresh没有写入/lain/deployd/operating

### ISSUE THREAD

**Issue by yuyang0** [laincloud/deployd#44]
最新版本出现了非常多这样的日志

>  deployd[28391]: 2018/02/08 11:13:21 WARN engine.go:683: [Store] Failed to remove operating pod group /lain/deployd/operating/hello-world.web.web, 100: Key not found (/lain/deployd/operating/hello-world.web.web) [9024081]

应该是pgCtl的Refresh中缺少

    pgCtrl.emitOperationEvent(OperationStart)

造成的， @supermeng 请确认一下

**Comment by supermeng** [comment]
这个是设计上的一点瑕疵，因为fresh不属于操作, 所以当时就没有将其加入operating， 但是重启的时候operating 是调用fresh去将未完成的工作完成，所以调用了一次pgOperOver清理operating的操作，所以每次refresh会有找不到key的错误。

**Comment by yuyang0** [comment]
也就是说这是正常的?

**Comment by supermeng** [comment]
恩恩，是的。不过我觉得好像让fresh也加入operating列表好像从语义上也说的过去，我再想想看吧

**Comment by yuyang0** [comment]
我觉得把Refresh作为一个操作确实没有什么大问题
