### ISSUE TITLE
pgOperRefreshInstance没有处理RunStateFail

### ISSUE THREAD

**Issue by yuyang0** [laincloud/deployd#45]
这在一些情况下会导致容器一直无法拉起，直接stop docker等一段时间在start， 那么那些不能迁移到其他节点的容器应该永远也无法拉起，我不确定是不是bug，但是我在RunStateExit分支添加RunStateFail后正常。 @supermeng

**Comment by supermeng** [comment]
恩恩，下次遇到拉不起来的容器，可以inspect一下容器状态吗？之前的设计是 RunStateFail 是属于调用docker api出现问题的状态，比如inspect , create, stop start container 返回了err，所以认为此节点是有问题的。所以没处理 RunStateFail 状态的，如果节点正常而 拉不起来就是这里有bug了。

**Comment by supermeng** [comment]
我看了一下应该是这里代码不对，不需要判断是不是有Error
             if !state.Running {
			if state.Error != "" {
				pc.pod.State = RunStateFail
				pc.pod.LastError = state.Error
			} else {
				pc.pod.State = RunStateExit
			}
		}

**Comment by supermeng** [comment]
这部分是我后面添加的设计，所以有些地方没写完全，我修一下这个问题。

**Comment by yuyang0** [comment]
这次测试docker 挂掉的场景一下炸出好几个问题，cluster monitor的部分有问题，我发现engine_disconnect会重复发送，最终导致deployd认为短时间挂了很多节点，直接退出，我来改一下 @supermeng

**Comment by supermeng** [comment]
哈哈，hin强，可以可以。deployd这部分代码确实bug还挺多的 ^_^

**Comment by supermeng** [comment]
@yuyang0 https://github.com/laincloud/deployd/pull/46 review一下
