### ISSUE TITLE
非常多watch event

### ISSUE THREAD

**Issue by yuyang0** [laincloud/deployd#48]
/lain/deployd/leader的值并没有修改，但是大概每隔5s就一个watch event，这正常吗？@supermeng

**Comment by supermeng** [comment]
是docker events？

**Comment by yuyang0** [comment]
etcd

**Comment by supermeng** [comment]
可以发一下日志吗？ 你说的应该是elector 选主的时候的问题，这可能发生在etcd出问题或者网络抖动

**Comment by yuyang0** [comment]
> Feb 09 15:13:39 gee030 deployd[93769]: 2018/02/09 15:13:39 DEBUG elect.go:89: Get watch event, leader value changed to 10.0.0.30:9003 
Feb 09 15:13:45 gee030 deployd[93769]: 2018/02/09 15:13:45 DEBUG elect.go:89: Get watch event, leader value changed to 10.0.0.30:9003 
Feb 09 15:13:52 deployd[93769]: 2018/02/09 15:13:52 DEBUG elect.go:89: Get watch event, leader value changed to 10.0.0.30:9003 
Feb 09 15:13:59 deployd[93769]: 2018/02/09 15:13:59 DEBUG elect.go:89: Get watch event, leader value changed to 10.0.0.30:9003
Feb 09 15:14:05 deployd[93769]: 2018/02/09 15:14:05 DEBUG elect.go:89: Get watch event, leader value changed to 10.0.0.30:9003

我使用命令行watch也会收到，我看了代码可能是那个Lock的问题，不确定

**Comment by supermeng** [comment]
恩恩，好像那个watcher确实有点问题，我看一下。

**Comment by supermeng** [comment]
看了一下，应该是locker每隔l.ttl / 3( 20 /3 = 7 )s左右会刷新一下ttl, 所以watcher会每7s左右推送一次事件。

**Comment by yuyang0** [comment]
这就是说，没办法咯，虽然其实也没大问题，不过感觉怪怪的

**Comment by supermeng** [comment]
恩恩，这没问题吧，etcdv2好像 watcher没支持忽略ttl的参数，我写一下注释吧，确实 不去看代码会难以理解
